### ISSUE TITLE
HDPI Screen, texts are too small

### ISSUE THREAD

**Issue by luismartinez03** [tanjinbd/GPTrainTrack2#1]
On my HDPI screen phone the app UI is having empty space and text icons are too small. 

My Handset info: 
Samsung Galaxy S9 ·
Android 10, 
256GB storage

Also let me know the layout XML that has been used for HDPI screen, I can work on that

**Comment by tanjinbd** [comment]
@luismartinez03 , 
For HDPI graphic asset, root dir: GPTrainTrack2\res\drawable-hdpi

For greater compatibility from Android Gingerbread I have used static Android Layout with: (Supports upto MDPI)
  <ScrollView  <ScrollView>       
        android:layout_width="fill_parent"
        android:layout_height="fill_parent"
        android:layout_gravity="center"
        android:background="@drawable/backrepeat"
        android:scrollbars="vertical" >

        <TableLayout     
            android:id="@+id/tableLayout1"
            android:layout_width="fill_parent"
            android:layout_height="fill_parent"
            android:layout_gravity="center_horizontal"
            android:gravity="center" >
            ....
            </TableLayout>   
     </ScrollView>   

A new layout with HDPI related attribute will fix the issue you have specified.

**Comment by tanjinbd** [comment]
> @luismartinez03 , For HDPI graphic asset, root dir: GPTrainTrack2\res\drawable-hdpi
> 
> For greater compatibility from Android Gingerbread I have used static Android Layout with: (Supports upto MDPI) <ScrollView android:layout_width="fill_parent" android:layout_height="fill_parent" android:layout_gravity="center" android:background="@drawable/backrepeat" android:scrollbars="vertical" >
> 
> ```
>     <TableLayout     
>         android:id="@+id/tableLayout1"
>         android:layout_width="fill_parent"
>         android:layout_height="fill_parent"
>         android:layout_gravity="center_horizontal"
>         android:gravity="center" >
>         ....
>         </TableLayout>   
>  </ScrollView>   
> ```
> 
> A new layout with HDPI related attribute will fix the issue you have specified.

@luismartinez03 , please check it fixes your screensize/res issues

**Comment by luismartinez03** [comment]
> > @luismartinez03 , For HDPI graphic asset, root dir: GPTrainTrack2\res\drawable-hdpi
> > For greater compatibility from Android Gingerbread I have used static Android Layout with: (Supports upto MDPI) 
> > ```
> >     <TableLayout     
> >         android:id="@+id/tableLayout1"
> >         android:layout_width="fill_parent"
> >         android:layout_height="fill_parent"
> >         android:layout_gravity="center_horizontal"
> >         android:gravity="center" >
> >         ....
> >         </TableLayout>   
> >  </ScrollView>   
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > A new layout with HDPI related attribute will fix the issue you have specified.
> 
> @luismartinez03 , please check it fixes your screensize/res issues

Yes, it fixed the issue

**Comment by tanjinbd** [comment]
@luismartinez03 , Thanks for the confirmation
